### PR TITLE
*ACES* to *sRGB* Primaries + Transfer Function should be called "sRGB - Camera" to be consistent with other spaces

### PR DESCRIPTION
**Pull request by mjmvisser**
Hi, I've been experimenting with aces-dev and added a new set of sRGB ODTs without the D60 simulation (for use on sRGB workstations that have already been calibrated to a D60 whitepoint). To be consistent with the rec.709 ODTs, I called them:

ODT.Academy.RGBmonitor_100nits_dim.a1.0.0.ctl

```
// <ACEStransformID>ODT.Academy.RGBmonitor_100nits_dim.a1.0.0</ACEStransformID>
// <ACESuserName>ACES 1.0 Output - sRGB</ACESuserName>
```

InvODT.Academy.RGBmonitor_100nits_dim.a1.0.0.ctl

```
// <ACEStransformID>InvODT.Academy.RGBmonitor_100nits_dim.a1.0.0</ACEStransformID>
// <ACESuserName>ACES 1.0 Inverse Output - sRGB</ACESuserName>
```

But then create_aces_config fails, because in general.py, a colorspace is added called "sRGB" (same name). I think this should be "sRGB - Camera" to be consistent with "Rec.709 - Camera", "Rec.2020 - Camera", etc..

### CODE REVIEW

**Comment by hpd** [comment]
Hi Mark,

Can you change the string in your ODT to "ACES 1.0 Output - sRGB D65" or
something else that doesn't conflict directly with the 'sRGB' name?

sRGB is a specification for encoding and display, so it's not as reasonable
to add a '- Camera' suffix to that colorspace name.

Regards,
HP

**Comment by mjmvisser** [comment]
How about "sRGB - Display"? That would be consistent with "Rec.709 - Display".

Though there are lots of digital cameras that capture in sRGB.

**Comment by mjmvisser** [comment]
Hi HP,

Actually, the ODT is named consistently with the Rec709 ODTs:

ODT.Academy.Rec709_100nits_dim.a1.0.0.ctl
ODT.Academy.Rec709_D60sim_100nits_dim.a1.0.0.ctl

ODT.Academy.RGBmonitor_100nits_dim.a1.0.0.ctl
ODT.Academy.RGBmonitor_D60sim_100nits_dim.a1.0.0.ctl

I agree that "sRGB" is rather vague, but I'm just following the existing conventions. Also, it's not accurate to name the non-D60 sim version "D65" because it's intended to be used on an sRGB display that has been hardware-level calibrated to have a D60 whitepoint (like the Rec709 version). This is the forum post that inspired me to create this ODT: https://groups.google.com/d/msg/academyaces/N85bt9Aqn48/7Mg_qh7qbeoJ

As for "sRGB - Camera": that's a fair point. How about "sRGB - Display"? That would be consistent with the existing "Rec.709 - Display" colorspace in general.py. Though to be pedantic, there are plenty of digital cameras that capture directly to sRGB, so it's a de facto standard capture space as well as an encoding and display.

all the best,
-Mark

**Comment by hpd** [comment]
Hello Mark,

The 'sRGB' colorspace has been renamed 'sRGB - Texture'. The change is
committed to github.

Hope that helps,
HP

**Pull request closed without merging**
