### PR TITLE
Various ACES 1.0.1 updates / fixes

### PR DESCRIPTION
**Pull request by selfshadow**

### CODE REVIEW

**Comment by hpd** [comment]
Thanks for the update. I'm going to wait to rename and regenerate the LUTs
until the ACES dev team has made the updates to the CTL available in the
hotfixes branch. I want it to be explicit about what transforms were used
to generate the LUTs, and the hotfixes branch is supposed to be the source
we use where there are critical fixes after a release.

I hope that the promotion of the commits from the dev branch to the
hotfixes branch will happen this week.

One other note, it looks like you're including the intermediate images, the
*.transformed.exr and *.float.tiff files, in your commit. Those are only
intermediate data, so the plan was not to check them in.

HP

**Comment by thomasmansencal** [comment]
> One other note, it looks like you're including the intermediate images, the
> *.transformed.exr and *.float.tiff files, in your commit. Those are only
> intermediate data, so the plan was not to check them in.

We should probably exclude them from the repo using the **.gitignore** file.

**Comment by selfshadow** [comment]
> One other note, it looks like you're including the intermediate images, the *.transformed.exr and *.float.tiff files, in your commit. Those are only intermediate data, so the plan was not to check them in. 

Ah yes, I should have checked on that when I saw those extra files opened for addition. Sorry about that.

> I hope that the promotion of the commits from the dev branch to the hotfixes branch will happen this week.

Again, I probably should have checked with you first about this. I wasn't sure how closely you were following aces-dev/dev; waiting for a hotfixes update makes sense.

Would you like a PR without the LUT changes?

> We should probably exclude them from the repo using the .gitignore file.

Good idea.

**Comment by hpd** [comment]
A PR with the updates to the init.py would be great. Were there other
changes not related to the updated CTL?

Thanks!
HP

**Comment by selfshadow** [comment]
> A PR with the updates to the init.py would be great.

Sure, I'll do that presently.

> Were there other changes not related to the updated CTL?

aces1.0.1/config.ocio was updated in the last commit, when I regenerated with `create_aces_config`, on account of the recent (wider) log shapers. However, I'm guessing you're aware of this and were holding off submitting this and the shaper LUT files for now.

**Comment by hpd** [comment]
> A PR with the updates to the init.py would be great.
> 
> Sure, I'll do that presently.
> 
> Pull request accepted. Thanks.
> 
> Were there other changes not related to the updated CTL?
> 
> aces1.0.1/config.ocio was updated in the last commit, when I regenerated
> with create_aces_config, on account of the recent (wider) log shapers.
> However, I'm guessing you're aware of this and were hold off submitting
> this and the shaper LUT files for now.
> 
> As far as I can see, the only changes to the config.ocio were the related
> to renaming the LUTs and colorspaces that referenced 2084. Those updates to
> config.ocio will be included in the commit that includes the renamed LUTs.

**Comment by selfshadow** [comment]
> As far as I can see, the only changes to the config.ocio were the related to renaming the LUTs and colorspaces that referenced 2084. Those updates to config.ocio will be included in the commit that includes the renamed LUTs.

Well, I'd manually replaced 2048 with 2084 in the first commit in the PR, but when the config was updated via `create_aces_config` (last commit in the PR), I got these additional diffs that seemed to relate to your recent shaper additions:

https://github.com/selfshadow/OpenColorIO-Configs/commit/ff8bed529629a279e1e4dcb2b1bbfd929b373e7e#diff-5b153470958c052133427e66470f52fc

**Comment by selfshadow** [comment]
> Well, I'd manually replaced 2048 with 2084 in the first commit in the PR, but when the config was updated via `create_aces_config` (last commit in the PR), I got these additional diffs that seemed to relate to your recent shaper additions

Ignore this. It looks as though I must have tested rebuilding the config whilst in the middle of other changes, which lead to a switch to 48 nit shapers in my first commit. I'll be way more careful next time!

**Pull request closed without merging**
